nomecom = input("Digite seu nome completo: ")
nascimento = input("Digite sua data de nascimento: ")
genero = input("Qual seu gênero? ")
altura = input("Digite sua altura (em Centímetros): ")
peso = input("Digite seu peso atual: ")

print(f"\nSeu nome completo é {nomecom}")
print(f"Sua data de nascimento é {nascimento}")
print(f"Seu gênero é {genero}")
print(f"Você tem {altura} centímetros de altura")
print(f"Você tem {peso}Kg inicialmente")
